// templates/vue/src/components/Notification.vue
<template>
  <div class="notification">
    <aside>
      <a target="_blank" rel="noreferrer" v-bind:href="urlPrefix + '/' + accountId">{{ accountId }}</a>
      <br />
      {{ msg }}
      <br />in contract:
      <a
        target="_blank"
        rel="noreferrer"
        v-bind:href="urlPrefix + '/' + contractId"
      >{{ contractId }}</a>
      <footer>
        <div>✔ Succeeded</div>
        <div>Just now</div>
      </footer>
    </aside>
  </div>
</template>

<script>
export default {
  name: "Notification",
  props: {
    networkId: String,
    msg: String,
  },
  computed: {
    urlPrefix() {
      return "https://explorer." + this.networkId + ".near.org/accounts"
    },
    accountId() {
      return window.accountId
    },
    contractId() {
      return window.contract? window.contractId: null
    },
  },
}
</script>

// templates/angular/src/app/components/notification/notification.component.ts
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';

import getConfig from '../../../config';
const { networkId } = getConfig(process.env.NODE_ENV || 'development');

@Component({
  selector: 'app-notification[accountId][contractId]',
  templateUrl: './notification.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NotificationComponent {
  @Input() accountId: string;
  @Input() contractId: string;
  urlPrefix = `https://explorer.${networkId}.near.org/accounts`;

  get accountUrl(): string {
    return `${this.urlPrefix}/${this.accountId}`;
  }

  get contractUrl(): string {
    return `${this.urlPrefix}/${this.contractId}`;
  }
}

<aside>
  <a target="_blank" rel="noreferrer" [href]="accountUrl">
    {{ accountId }}
  </a>
  <a target="_blank" rel="noreferrer" [href]="contractUrl">
    {{ contractId }}
  </a>
  <footer>
    <div>✔ Succeeded</div>
    <div>Just now</div>
  </footer>
</aside>
