// templates/react/src/App.js
import 'regenerator-runtime/runtime'
import React from 'react'
import { login, logout } from './utils'
import './global.css'

import getConfig from './config'
const { networkId } = getConfig(process.env.NODE_ENV || 'development')

export default function App() {
  // use React Hooks to store greeting in component state
  const [greeting, setGreeting] = React.useState()

  // when the user has not yet interacted with the form, disable the button
  const [buttonDisabled, setButtonDisabled] = React.useState(true)

  // after submitting the form, we want to show Notification
  const [showNotification, setShowNotification] = React.useState(false)

  // The useEffect hook can be used to fire side-effects during render
  // Learn more: https://reactjs.org/docs/hooks-intro.html
  React.useEffect(
    () => {
      // in this case, we only care to query the contract when signed in
      if (window.walletConnection.isSignedIn()) {

        // window.contract is set by initContract in index.js
        window.contract.getGreeting({ accountId: window.accountId })
          .then(greetingFromContract => {
            setGreeting(greetingFromContract)
          })
      }
    },

    // The second argument to useEffect tells React when to re-run the effect
    // Use an empty array to specify "only run on first render"
    // This works because signing into NEAR Wallet reloads the page
    []
  )

  // if not signed in, return early with sign-in prompt
  if (!window.walletConnection.isSignedIn()) {
    return (
      <main>
        <h1>Welcome to NEAR!</h1>
        <p>
          To make use of the NEAR blockchain, you need to sign in. The button
          below will sign you in using NEAR Wallet.
        </p>
        <p>
          By default, when your app runs in "development" mode, it connects
          to a test network ("testnet") wallet. This works just like the main
          network ("mainnet") wallet, but the NEAR Tokens on testnet aren't
          convertible to other currencies – they're just for testing!
        </p>
        <p>
          Go ahead and click the button below to try it out:
        </p>
        <p style={{ textAlign: 'center', marginTop: '2.5em' }}>
          <button onClick={login}>Sign in</button>
        </p>
      </main>
    )
  }

  return (
    // use React Fragment, <>, to avoid wrapping elements in unnecessary divs
    <>
      <button className="link" style={{ float: 'right' }} onClick={logout}>
        Sign out
      </button>
      <main>
        <h1>
          <label
            htmlFor="greeting"
            style={{
              color: 'var(--secondary)',
              borderBottom: '2px solid var(--secondary)'
            }}
          >
            {greeting}
          </label>
          {' '/* React trims whitespace around tags; insert literal space character when needed */}
          {window.accountId}!
        </h1>
        <form onSubmit={async event => {
          event.preventDefault()

          // get elements from the form using their id attribute
          const { fieldset, greeting } = event.target.elements

          // hold onto new user-entered value from React's SynthenticEvent for use after `await` call
          const newGreeting = greeting.value

          // disable the form while the value gets updated on-chain
          fieldset.disabled = true

          try {
            // make an update call to the smart contract
            await window.contract.setGreeting({
              // pass the value that the user entered in the greeting field
              message: newGreeting
            })
          } catch (e) {
            alert(
              'Something went wrong! ' +
              'Maybe you need to sign out and back in? ' +
              'Check your browser console for more info.'
            )
            throw e
          } finally {
            // re-enable the form, whether the call succeeded or failed
            fieldset.disabled = false
          }

          // update local `greeting` variable to match persisted value
          setGreeting(newGreeting)

          // show Notification
          setShowNotification(true)

          // remove Notification again after css animation completes
          // this allows it to be shown again next time the form is submitted
          setTimeout(() => {
            setShowNotification(false)
          }, 11000)
        }}>
          <fieldset id="fieldset">
            <label
              htmlFor="greeting"
              style={{
                display: 'block',
                color: 'var(--gray)',
                marginBottom: '0.5em'
              }}
            >
              Change greeting
            </label>
            <div style={{ display: 'flex' }}>
              <input
                autoComplete="off"
                defaultValue={greeting}
                id="greeting"
                onChange={e => setButtonDisabled(e.target.value === greeting)}
                style={{ flex: 1 }}
              />
              <button
                disabled={buttonDisabled}
                style={{ borderRadius: '0 5px 5px 0' }}
              >
                Save
              </button>
            </div>
          </fieldset>
        </form>
        <p>
          Look at that! A Hello World app! This greeting is stored on the NEAR blockchain. Check it out:
        </p>
        <ol>
          <li>
            Look in <code>src/App.js</code> and <code>src/utils.js</code> – you'll see <code>getGreeting</code> and <code>setGreeting</code> being called on <code>contract</code>. What's this?
          </li>
          <li>
            Ultimately, this <code>contract</code> code is defined in <code>contract/assembly/index.ts</code> – this is the source code for your <a target="_blank" rel="noreferrer" href="https://docs.near.org/docs/roles/developer/contracts/intro">smart contract</a>.</li>
          <li>
            When you run <code>yarn dev</code>, the code in <code>contract/assembly/index.ts</code> gets deployed to the NEAR testnet. You can see how this happens by looking in <code>package.json</code> at the <code>scripts</code> section to find the <code>dev</code> command.</li>
        </ol>
        <hr />
        <p>
          To keep learning, check out <a target="_blank" rel="noreferrer" href="https://docs.near.org">the NEAR docs</a> or look through some <a target="_blank" rel="noreferrer" href="https://examples.near.org">example apps</a>.
        </p>
      </main>
      {showNotification && <Notification />}
    </>
  )
}

// this component gets rendered by App after the form is submitted
function Notification() {
  const urlPrefix = `https://explorer.${networkId}.near.org/accounts`
  return (
    <aside>
      <a target="_blank" rel="noreferrer" href={`${urlPrefix}/${window.accountId}`}>
        {window.accountId}
      </a>
      {' '/* React trims whitespace around tags; insert literal space character when needed */}
      called method: 'setGreeting' in contract:
      {' '}
      <a target="_blank" rel="noreferrer" href={`${urlPrefix}/${window.contract.contractId}`}>
        {window.contract.contractId}
      </a>
      <footer>
        <div>✔ Succeeded</div>
        <div>Just now</div>
      </footer>
    </aside>
  )
}

// templates/angular/src/app/app.component.ts
import { Component, Inject, OnInit } from '@angular/core'

import { login, logout } from '../utils'
import { WINDOW } from './services/window.service'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html'
})
export class AppComponent implements OnInit {
  greeting: string
  newGreeting: string
  showNotification = false

  get accountId(): string {
    return this.window.walletConnection.getAccountId()
  }

  get signedIn(): boolean {
    return this.window.walletConnection.isSignedIn()
  }

  get contractId(): string {
    return this.window.contract.contractId
  }

  get buttonDisabled(): boolean {
    const newGreeting = this.newGreeting?.trim()
    return !newGreeting || newGreeting === this.greeting
  }

  constructor(@Inject(WINDOW) private window: Window) {}

  ngOnInit(): void {
    this.fetchGreeting()
  }

  login(): void {
    login()
  }

  logout(): void {
    logout()
  }

  async fetchGreeting(): Promise<void> {
    if (this.signedIn) {
      this.greeting = this.newGreeting = await this.window.contract.getGreeting({ accountId: this.accountId })
    }
  }

  async onSubmit(event): Promise<void> {
    event.preventDefault()

    // get elements from the form using their id attribute
    const { fieldset, greeting } = event.target.elements

    // disable the form while the value gets updated on-chain
    fieldset.disabled = true

    try {
      // make an update call to the smart contract
      await this.window.contract.setGreeting({ message: greeting.value })
    } catch (e) {
      alert(
        'Something went wrong! ' +
        'Maybe you need to sign out and back in? ' +
        'Check your browser console for more info.'
      )
      throw e
    } finally {
      // re-enable the form, whether the call succeeded or failed
      fieldset.disabled = false
    }

    // update local `greeting` variable to match persisted value
    this.greeting = this.newGreeting

    // show notification
    this.showNotification = true

    // remove notification again after css animation completes
    // this allows it to be shown again next time the form is submitted
    setTimeout(() => {
      this.showNotification = false
    }, 11000)
  }
}

<ng-container [ngSwitch]="signedIn">
  <ng-container *ngSwitchCase="true" [ngTemplateOutlet]="signedInTemplate"></ng-container>
  <ng-container *ngSwitchDefault [ngTemplateOutlet]="signedOutTemplate"></ng-container>
</ng-container>

<ng-template #signedInTemplate>
  <button [ngStyle]="{ float: 'right' }" (click)="logout()">Sign out</button>
  <main>
    <h1>
      <label [ngStyle]="{
        color: 'var(--secondary)',
        borderBottom: '2px solid var(--secondary)'
      }" [innerHTML]="greeting"></label>
      {{ accountId }}
    </h1>
    <form (ngSubmit)="onSubmit($event)">
      <fieldset id="fieldset">
        <label for="greeting" [ngStyle]="{
          display: 'block',
          color: 'var(--gray)',
          marginBottom: '0.5em'
        }">Change greeting</label>
        <div [ngStyle]="{ display: 'flex' }">
          <input
            [ngStyle]="{ flexGrow: 1 }"
            type="text"
            id="greeting"
            name="greeting"
            autoComplete="off"
            [(ngModel)]="newGreeting"
            [defaultValue]="greeting"
            required
          />
          <button [ngStyle]="{ borderRadius: '0 5px 5px 0' }" type="submit" [disabled]="buttonDisabled">Save</button>
        </div>
      </fieldset>
    </form>
    <p>
      Look at that! A Hello World app! This greeting is stored on the NEAR blockchain. Check it out:
    </p>
    <ol>
      <li>
        Look in <code>src/app/app.component.ts</code> and <code>src/utils.js</code>
        - you'll see <code>getGreeting</code>
        and <code>setGreeting</code> being called on <code>contract</code>. What's this?
      </li>
      <li>
        Ultimately, this <code>contract</code> code is defined in <code>contract/assembly/index.ts</code>
        - this is the source code for your
        <a target="_blank" rel="noreferrer" href="https://docs.near.org/docs/roles/developer/contracts/intro">smart contract</a>.
      </li>
      <li>
        When you run <code>yarn dev</code>, the code in <code>contract/assembly/index.ts</code>
        gets deployed to the NEAR testnet. You can see how this happens by looking in <code>package.json</code>
        at the <code>scripts</code> section to find the <code>dev</code> command.
      </li>
    </ol>
    <hr />
    <p>
      To keep learning, check out <a target="_blank" rel="noreferrer" href="https://docs.near.org">the NEAR docs</a> or look through some
      <a target="_blank" rel="noreferrer" href="https://examples.near.org">example apps</a>.
    </p>
  </main>
  <app-notification [accountId]="accountId" [contractId]="contractId" *ngIf="showNotification"></app-notification>
</ng-template>

<ng-template #signedOutTemplate>
  <main>
    <h1>Welcome to NEAR!</h1>
    <p>
      To make use of the NEAR blockchain, you need to sign in. The button
      below will sign you in using NEAR Wallet.
    </p>
    <p>
      By default, when your app runs in "development" mode, it connects
      to a test network ("testnet") wallet. This works just like the main
      network ("mainnet") wallet, but the NEAR Tokens on testnet aren't
      convertible to other currencies – they're just for testing!
    </p>
    <p>
      Go ahead and click the button below to try it out:
    </p>
    <p [ngStyle]="{ textAlign: 'center', marginTop: '2.5em' }">
      <button type="button" (click)="login()">Sign in</button>
    </p>
  </main>
</ng-template>
