// templates/react/src/index.js
import React from "react";
import { createRoot } from "react-dom/client";
import App from "./App";
import { initContract } from "./utils";

const container = document.querySelector("#root");
const root = createRoot(container); // createRoot(container!) if you use TypeScript

window.nearInitPromise = initContract()
  .then(() => {
    <App />;
    root.render(<App tab="home" />);
  })
  .catch(console.error);

// templates/angular/src/main.ts
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from './app/app.module';
import { environment } from './environments/environment';
import { initContract } from './utils';

if (environment.production) {
  enableProdMode();
}

window.nearInitPromise = initContract()
  .then(() =>
    platformBrowserDynamic().bootstrapModule(AppModule).catch(err => console.error(err))
  );
